### PR TITLE
Made it work and improve protocol checker and made a test webpage for esp8266

### PR DESCRIPTION
**Pull request by leopck**
Made it work.
Just flash into esp8266.
Access esp8266 webpage using smartphone
Click on the button.
Profit ??? and watch that websocket echo back the letter 'e'
https://github.com/cnlohr/espusb/issues/23

### CODE REVIEW

**Comment by T-vK** [comment]
I'll test it later today. I wonder what made it work. I mean the protocol check shouldn't have changed anything. The only thing I can think of right now is that the esp crashed when the client is still downloading files from the esp and starts the socket at the same time.

**Comment by leopck** [comment]
Hmmmmm.... As embarrassing as it sounds for me.... But initially I git cloned your repo and it couldn't work, there was some ws issue, I made some changes along the line but nothing to your codes. After flashing the website, it suddenly worked for me.

Hence, I named the commit 'a2b1eb0' as "Magically works now...."
[https://github.com/T-vK/Responding-Websockets/pull/1/commits/a2b1eb0234093662af25861735c40fe0efffaff5](https://github.com/T-vK/Responding-Websockets/pull/1/commits/a2b1eb0234093662af25861735c40fe0efffaff5)

I have no idea what made it work but it wasn't working for me initially too however, after a few tries, it works.... Hence, MAGIC. 

Jokes aside.... I think your codes were already working initially. No issue on your codes probably. So I just touched up a few things.

**Comment by leopck** [comment]
Regarding your statement on esp crashed when the client is still downloading files from esp and start the socket at the same time.... That might actually make LOTS OF SENSE! Because initially, I wrote the index.html to start the websocket as soon as possible.

Now if you check my codes... I made it run only when clicked. And once I do that, it worked. So your guess might be correct. I'm going to re-verify this again.

EDIT: Re-tested, I can't seem to replicate the same issue anymore :( If you still have the problem persisting using the codes above then we need to investigate further.

**Comment by T-vK** [comment]
Apparently it happens when you send "WS". Sending "e" works just fine.

**Comment by leopck** [comment]
Strange? Because I can send "WS". I get a reply from esp with "WS1" but I can send "WS" with no issue though.

**Pull request merged**
